Save the fact that content is an ical content
u01jmg3/ics-parser pull request #336
Opened 2024-04-11 23:07 UTC by axi

The parser does already the job, so we can use it to "validate" it's really an ical content.

2024-04-12 02:32 UTC, u01jmg3 requested changes

2024-04-12 02:32 UTC, u01jmg3 commented on src/ICal/ICal.php
> +                [$k, $v] = explode('=', $s);
Please revert this unmentioned change

2024-04-12 15:09 UTC, axi commented on src/ICal/ICal.php
> +                [$k, $v] = explode('=', $s);
Sure, I missed this one

2024-04-22 17:56 UTC, axi commented
Hey @u01jmg3, could you check this PR ? Thanks

2024-04-22 18:01 UTC, axi commented
just thinking about this, I'm using the parser in a loop and before passing it a new url to parse, I have to 
```
                // Reset from potential previous iteration
                $ical->cal = [];
                $ical->isIcalContent = false;
```
Should'nt that be in a new `reset()` method ?
I can update the PR (or create a new one probably)

2024-04-22 21:44 UTC, u01jmg3 commented
I've sat on this one for a bit and I don't think knowing that a file starts with `BEGIN:VCALENDAR` is enough to say you've validated it as iCal content.

I think if you need this in your code you should track it yourself.

2024-04-22 21:44 UTC, closed without merging

2024-04-22 23:30 UTC, axi commented
Ok. For reference,  this would probably be the minimum for validating a ical content: https://stackoverflow.com/a/67698638/2454746